BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS item (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    ingame_id TEXT NOT NULL,
    save_id INTEGER NOT NULL,
    level_index INTEGER NOT NULL,
    collected INTEGER NOT NULL,
    x REAL NOT NULL,
    y REAL NOT NULL,
    FOREIGN KEY(save_id) REFERENCES save(id)
);

CREATE TABLE IF NOT EXISTS enemy (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    ingame_id TEXT NOT NULL,
    save_id INTEGER NOT NULL,
    level_index INTEGER NOT NULL,
    health INTEGER NOT NULL,
    is_dead INTEGER NOT NULL,
    x INTEGER NOT NULL,
    y INTEGER NOT NULL,
    FOREIGN KEY(save_id) REFERENCES save(id)
);

CREATE TABLE IF NOT EXISTS player (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    save_id INTEGER NOT NULL,
    facemask_count INTEGER NOT NULL,
    ammo_count INTEGER NOT NULL,
    has_gun INTEGER NOT NULL,
    x REAL NOT NULL,
    y REAL NOT NULL,
    spawn_x REAL NOT NULL,
    spawn_y REAL NOT NULL
    FOREIGN KEY(save_id) REFERENCES save(id)
);

CREATE TABLE IF NOT EXISTS save (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    level_index INTEGER NOT NULL,
    name TEXT NOT NULL,
    timestamp INTEGER NOT NULL
);

COMMIT;
